-- Create schema for Support ticket to review customer provided data.
-- mariadb_quick_review, by Edward Stoever for MariaDB Support

drop schema if exists $SCHEMA_NAME;
create schema $SCHEMA_NAME;
use $SCHEMA_NAME;

CREATE TABLE `SERVER_PERFORMANCE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` timestamp NOT NULL DEFAULT current_timestamp(),
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `REDO_LOG_OCCUPANCY_PCT` decimal(8,2) DEFAULT NULL,
  `THREADS_CONNECTED` int(11) DEFAULT NULL,
  `HANDLER_READ_RND_NEXT` bigint(20) DEFAULT NULL,
  `COM_SELECT` bigint(20) DEFAULT NULL,
  `COM_INSERT` bigint(20) DEFAULT NULL,
  `COM_UPDATE` bigint(20) DEFAULT NULL,
  `COM_DELETE` bigint(20) DEFAULT NULL,
  `COM_XA_COMMIT` bigint(20) DEFAULT NULL,
  `SLOW_QUERIES` bigint(20) DEFAULT NULL,
  `INNODB_ROW_LOCK_CURRENT_WAITS` bigint(20) DEFAULT NULL,
  `INNODB_BUFFER_POOL_READS` bigint(20) DEFAULT NULL,
  `INNODB_BUFFER_POOL_READ_REQUESTS` bigint(20) DEFAULT NULL,
  `MEMORY_USED` bigint(20) DEFAULT NULL,
  `BINLOG_COMMITS` bigint(20) DEFAULT NULL,
  `INNODB_BUFFER_POOL_BYTES_DATA` bigint(20) DEFAULT NULL,
  `INNODB_DATA_WRITES` bigint(20) DEFAULT NULL,
  `INNODB_OS_LOG_WRITTEN` bigint(20) DEFAULT NULL,
  `INNODB_HISTORY_LIST_LENGTH` bigint(20) DEFAULT NULL,
  `COM_STMT_PREPARE` bigint(20) DEFAULT NULL,
  `COM_STMT_EXECUTE` bigint(20) DEFAULT NULL,
  `QCACHE_QUERIES_IN_CACHE` bigint(20) DEFAULT NULL,
  `QCACHE_FREE_MEMORY` bigint(20) DEFAULT NULL,
  `QCACHE_HITS` bigint(20) DEFAULT NULL,
  `QCACHE_INSERTS` bigint(20) DEFAULT NULL,
  `QCACHE_LOWMEM_PRUNES` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `LOW_CARDINALITY_IDX` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TICK` datetime DEFAULT NULL,
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `ITEM` varchar(100) DEFAULT NULL,
  `STATUS` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `PERFORMANCE_WARNINGS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` datetime DEFAULT NULL,
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `ITEM` varchar(100) DEFAULT NULL,
  `STATUS` varchar(150) DEFAULT NULL,
  `INFO` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `REVIEW_WARNINGS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` datetime DEFAULT NULL,
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `ITEM` varchar(100) DEFAULT NULL,
  `STATUS` varchar(150) DEFAULT NULL,
  `INFO` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `GALERA_WARNINGS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` datetime DEFAULT NULL,
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `ITEM` varchar(100) DEFAULT NULL,
  `STATUS` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB   DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `GTID_POSITIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` timestamp NOT NULL DEFAULT current_timestamp(),
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `GTID_BINLOG_POS` varchar(200) comment 'The last event written to the binary log',
  `GTID_BINLOG_STATE` varchar(200) comment 'The last sequence per combination of domain_id and server_id in binary log history',
  `GTID_CURRENT_POS` varchar(200) comment 'The last transaction applied to the database',
  `GTID_SLAVE_POS` varchar(200) comment 'The last transaction applied to the database by the replica threads',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `TABLE_KEY_COUNTS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TABLE_SCHEMA` varchar(64) DEFAULT NULL,
  `TABLE_NAME` varchar(64) DEFAULT NULL,
  `ENGINE` varchar(64) DEFAULT NULL,
  `PRIMARY_KEY_COUNT` int(11) DEFAULT NULL,
  `UNIQUE_KEY_COUNT` int(11) DEFAULT NULL,
  `NON_UNIQUE_KEY_COUNT` int(11) DEFAULT NULL,
  `ROW_FORMAT` varchar(32) DEFAULT NULL,
  `TABLE_ROWS` bigint(21) DEFAULT NULL,
  `AVG_ROW_LENGTH` bigint(21) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SERVER_STATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SECTION_ID` int(11) NOT NULL,
  `ITEM` varchar(72) NOT NULL,
  `STATUS` varchar(72) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `PROCESSLIST` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` datetime DEFAULT NULL,
  `CONNECTION_ID` bigint(20) DEFAULT NULL,
  `USER` varchar(256) DEFAULT NULL,
  `HOST` varchar(128) DEFAULT NULL,
  `DB` varchar(128) DEFAULT NULL,
  `COMMAND` varchar(64) DEFAULT NULL,
  `TIME` int(11) DEFAULT NULL,
  `STATE` varchar(128) DEFAULT NULL,
  `INFO` longtext DEFAULT NULL,
  `TIME_MS` decimal(24,3) DEFAULT NULL,
  `STAGE` tinyint(4) DEFAULT NULL,
  `MAX_STAGE` tinyint(4) DEFAULT NULL,
  `PROGRESS` decimal(8,3) DEFAULT NULL,
  `MEMORY_USED` bigint(20) DEFAULT NULL,
  `MAX_MEMORY_USED` bigint(20) DEFAULT NULL,
  `EXAMINED_ROWS` int(11) DEFAULT NULL,
  `QUERY_ID` bigint(20) DEFAULT NULL,
  `TID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `GLOBAL_VARIABLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VARIABLE_NAME` varchar(64) NOT NULL,
  `VARIABLE_VALUE` varchar(2048) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `GLOBAL_STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VARIABLE_NAME` varchar(64) NOT NULL,
  `VARIABLE_VALUE` varchar(2048) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SECTION_TITLES` (
  `SECTION_ID` int(11) NOT NULL,
  `TITLE` varchar(72) NOT NULL,
  PRIMARY KEY (`SECTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `SECTION_TITLES` VALUES (1,'SERVER'),(2,'TOPOLOGY'),(3,'SCHEMAS'),(4,'PERFORMANCE'),(5,'GLOBALS'),(6,'WARNINGS'),(7,'GALERA');

CREATE TABLE IF NOT EXISTS `GALERA_MARIADB_VERSIONS` (
  `galera_version` varchar(20) NOT NULL,
  `mariadb_version` varchar(20) NOT NULL,
  PRIMARY KEY (`galera_version`,`mariadb_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `GALERA_MARIADB_VERSIONS` VALUES ('26.4.0','10.4.2'),('26.4.1','10.4.3'),('26.4.11','10.4.22'),
  ('26.4.11','10.4.23'),('26.4.11','10.4.24'),('26.4.11','10.4.25'),('26.4.11','10.5.14'),('26.4.11','10.5.15'),
  ('26.4.11','10.5.16'),('26.4.11','10.6.6'),('26.4.11','10.7.2'),('26.4.11','10.7.3'),('26.4.11','10.7.4'),
  ('26.4.11','10.8.1'),('26.4.11','10.8.2'),('26.4.11','10.8.3'),('26.4.12','10.10.1'),('26.4.12','10.4.26'),
  ('26.4.12','10.5.17'),('26.4.12','10.6.10'),('26.4.12','10.6.9'),('26.4.12','10.7.5'),('26.4.12','10.7.6'),
  ('26.4.12','10.8.4'),('26.4.12','10.8.5'),('26.4.12','10.9.2'),('26.4.12','10.9.3'),('26.4.13','10.10.2'),
  ('26.4.13','10.4.27'),('26.4.13','10.5.18'),('26.4.13','10.6.11'),('26.4.13','10.7.7'),('26.4.13','10.8.6'),
  ('26.4.13','10.9.4'),('26.4.14','10.10.3'),('26.4.14','10.4.28'),('26.4.14','10.4.29'),('26.4.14','10.4.30'),
  ('26.4.14','10.5.19'),('26.4.14','10.5.20'),('26.4.14','10.5.21'),('26.4.14','10.6.12'),('26.4.14','10.6.13'),
  ('26.4.14','10.6.14'),('26.4.14','10.7.8'),('26.4.14','10.8.7'),('26.4.14','10.9.5'),('26.4.2','10.4.4'),
  ('26.4.2','10.4.5'),('26.4.2','10.4.6'),('26.4.2','10.4.7'),('26.4.2','10.4.8'),('26.4.3','10.4.9'),
  ('26.4.3','10.5.0'),('26.4.4','10.4.13'),('26.4.4','10.5.1'),('26.4.4','10.5.2'),('26.4.4','10.5.3'),
  ('26.4.5','10.4.14'),('26.4.5','10.4.15'),('26.4.5','10.5.4'),('26.4.5','10.5.5'),('26.4.6','10.4.16'),
  ('26.4.6','10.4.17'),('26.4.6','10.5.7'),('26.4.6','10.5.8'),('26.4.7','10.4.18'),('26.4.7','10.5.9'),
  ('26.4.8','10.4.19'),('26.4.8','10.4.20'),('26.4.8','10.5.10'),('26.4.8','10.5.11'),('26.4.8','10.6.1'),
  ('26.4.8','10.6.2'),('26.4.8','10.6.3'),('26.4.9','10.4.20'),('26.4.9','10.4.21'),('26.4.9','10.5.12'),
  ('26.4.9','10.5.13'),('26.4.9','10.6.4'),('26.4.9','10.6.5');

CREATE TABLE `GALERA_PERFORMANCE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` timestamp NOT NULL DEFAULT current_timestamp(),
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `WSREP_APPLIER_THREAD_COUNT` bigint(20) DEFAULT NULL,
  `WSREP_APPLY_OOOE` decimal(20,10) DEFAULT NULL,
  `WSREP_APPLY_OOOL` decimal(20,10) DEFAULT NULL,
  `WSREP_APPLY_WAITS` bigint(20) DEFAULT NULL,
  `WSREP_APPLY_WINDOW` decimal(20,10) DEFAULT NULL,
  `WSREP_CAUSAL_READS` bigint(20) DEFAULT NULL,
  `WSREP_CERT_DEPS_DISTANCE` decimal(20,10) DEFAULT NULL,
  `WSREP_CERT_INDEX_SIZE` bigint(20) DEFAULT NULL,
  `WSREP_CERT_INTERVAL` decimal(20,10) DEFAULT NULL,
  `WSREP_DESYNC_COUNT` bigint(20) DEFAULT NULL,
  `WSREP_EVS_DELAYED` varchar(256) DEFAULT NULL,
  `WSREP_EVS_EVICT_LIST` varchar(256) DEFAULT NULL,
  `WSREP_EVS_REPL_LATENCY` varchar(256) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_ACTIVE` varchar(20) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_PAUSED` decimal(20,10) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_PAUSED_NS` bigint(20) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_RECV` bigint(20) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_REQUESTED` varchar(20) DEFAULT NULL,
  `WSREP_FLOW_CONTROL_SENT` bigint(20) DEFAULT NULL,
  `WSREP_LAST_COMMITTED` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_BF_ABORTS` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_CACHED_DOWNTO` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_CERT_FAILURES` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_COMMITS` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_INDEX` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_RECV_QUEUE` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_RECV_QUEUE_AVG` decimal(20,10) DEFAULT NULL,
  `WSREP_LOCAL_RECV_QUEUE_MAX` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_RECV_QUEUE_MIN` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_REPLAYS` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_SEND_QUEUE` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_SEND_QUEUE_AVG` decimal(20,10) DEFAULT NULL,
  `WSREP_LOCAL_SEND_QUEUE_MAX` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_SEND_QUEUE_MIN` bigint(20) DEFAULT NULL,
  `WSREP_LOCAL_STATE_COMMENT` varchar(50) DEFAULT NULL,
  `WSREP_OPEN_CONNECTIONS` bigint(20) DEFAULT NULL,
  `WSREP_OPEN_TRANSACTIONS` bigint(20) DEFAULT NULL,
  `WSREP_RECEIVED` bigint(20) DEFAULT NULL,
  `WSREP_RECEIVED_BYTES` bigint(20) DEFAULT NULL,
  `WSREP_REPLICATED` bigint(20) DEFAULT NULL,
  `WSREP_REPLICATED_BYTES` bigint(20) DEFAULT NULL,
  `WSREP_REPL_DATA_BYTES` bigint(20) DEFAULT NULL,
  `WSREP_REPL_KEYS` bigint(20) DEFAULT NULL,
  `WSREP_REPL_KEYS_BYTES` bigint(20) DEFAULT NULL,
  `WSREP_REPL_OTHER_BYTES` bigint(20) DEFAULT NULL,
  `WSREP_ROLLBACKER_THREAD_COUNT` bigint(20) DEFAULT NULL,
  `WSREP_THREAD_COUNT` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SLAVE_STATUS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RUN_ID` varchar(16) DEFAULT NULL,
  `TICK` datetime DEFAULT NULL,
  `HOSTNAME` varchar(128) DEFAULT NULL,
  `SECONDS_BEHIND_MASTER` bigint(20) DEFAULT NULL,
  `GTID_IO_POS` varchar(250) DEFAULT NULL,
  `GTID_SLAVE_POS` varchar(250) DEFAULT NULL,
  `SLAVE_SQL_RUNNING_STATE` varchar(500) DEFAULT NULL,
  `LAST_SQL_ERROR` varchar(700) DEFAULT NULL,
  `LAST_IO_ERROR` varchar(700) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

