-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- FILE_SUMMARY_BY_INSTANCE

SELECT '$RUNID' as RUN_ID,
`FILE_NAME`,
`EVENT_NAME`,
`OBJECT_INSTANCE_BEGIN`,
`COUNT_STAR`,
`SUM_TIMER_WAIT`,
`MIN_TIMER_WAIT`,
`AVG_TIMER_WAIT`,
`MAX_TIMER_WAIT`,
`COUNT_READ`,
`SUM_TIMER_READ`,
`MIN_TIMER_READ`,
`AVG_TIMER_READ`,
`MAX_TIMER_READ`,
`SUM_NUMBER_OF_BYTES_READ`,
`COUNT_WRITE`,
`SUM_TIMER_WRITE`,
`MIN_TIMER_WRITE`,
`AVG_TIMER_WRITE`,
`MAX_TIMER_WRITE`,
`SUM_NUMBER_OF_BYTES_WRITE`,
`COUNT_MISC`,
`SUM_TIMER_MISC`,
`MIN_TIMER_MISC`,
`AVG_TIMER_MISC`,
`MAX_TIMER_MISC`
from performance_schema.file_summary_by_instance
limit 100000