-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- GTID_POSITIONS
-- RUN MULTIPLE TIMES
WITH GTID_VALUES AS (
SELECT
(select VARIABLE_VALUE from information_schema.GLOBAL_VARIABLES where VARIABLE_NAME='GTID_BINLOG_POS' limit 1) AS `GTID_BINLOG_POS`,
(select VARIABLE_VALUE from information_schema.GLOBAL_VARIABLES where VARIABLE_NAME='GTID_BINLOG_STATE' limit 1)AS `GTID_BINLOG_STATE`,
(select VARIABLE_VALUE from information_schema.GLOBAL_VARIABLES where VARIABLE_NAME='GTID_CURRENT_POS' limit 1) AS `GTID_CURRENT_POS`,
(select VARIABLE_VALUE from information_schema.GLOBAL_VARIABLES where VARIABLE_NAME='GTID_SLAVE_POS' limit 1) AS `GTID_SLAVE_POS`)
 SELECT '$SUBROUTINE',now(),@@hostname,GTID_BINLOG_POS,GTID_BINLOG_STATE,GTID_CURRENT_POS,GTID_SLAVE_POS from GTID_VALUES

