-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- IS_PERFORMANCE_SCHEMA_ENABLED
SELECT CONCAT('YES') AS PERFORMANCE_SCHEMA_ENABLED 
  FROM information_schema.GLOBAL_VARIABLES 
  WHERE VARIABLE_NAME ='PERFORMANCE_SCHEMA' AND VARIABLE_VALUE='ON'
  LIMIT 1
