-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- IS_USERSTAT_ENABLED
SELECT CONCAT('YES') AS USERSTAT_ENABLED 
  FROM information_schema.GLOBAL_VARIABLES 
  WHERE VARIABLE_NAME ='USERSTAT' AND VARIABLE_VALUE='ON'
  LIMIT 1
