-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- PROCESSLIST
-- RUN ONE TIME WITH OPTION TO RUN MULTIPLE TIMES
-- THE INFO COLUMN CAN HAVE LINEFEEDS AND THUS HAS THE OPTIONAL ENCLOSURE

select '$SUBROUTINE' as RUN_ID, now() as TICK, `ID` as CONNECTION_ID,`USER`,`HOST`,`DB`,`COMMAND`,`TIME`,`STATE`,CONCAT('$ENCLOSURE',REPLACE(`INFO`,'"',''),'$ENCLOSURE') as `INFO`,`TIME_MS`,`STAGE`,`MAX_STAGE`,`PROGRESS`,`MEMORY_USED`,`MAX_MEMORY_USED`,`EXAMINED_ROWS`,`QUERY_ID`,`TID` 
from information_schema.PROCESSLIST

