-- DISTRIBUTED WITH mariadb_quick_review by Edward Stoever for MariaDB Support
-- SERVER_PERFORMANCE
-- RUN MULTIPLE TIMES
select VARIABLE_VALUE into @LOG_FILE_CAPACITY 
    from information_schema.global_variables 
    where VARIABLE_NAME='INNODB_LOG_FILE_SIZE';

SELECT VARIABLE_VALUE INTO @CHECKPOINT_AGE
  FROM information_schema.GLOBAL_STATUS 
  WHERE VARIABLE_NAME='INNODB_CHECKPOINT_AGE';

SET @OCCUPANCY=format((@CHECKPOINT_AGE/@LOG_FILE_CAPACITY)*100,2);

SELECT '$SUBROUTINE' as RUN_ID, now() as TICK, @@hostname as HOSTNAME, @OCCUPANCY as REDO_LOG_OCCUPANCY_PCT,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='THREADS_CONNECTED') AS `THREADS_CONNECTED`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='HANDLER_READ_RND_NEXT') AS `HANDLER_READ_RND_NEXT`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_SELECT') AS `COM_SELECT`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_INSERT') AS `COM_INSERT`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_UPDATE') AS `COM_UPDATE`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_DELETE') AS `COM_DELETE`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_XA_COMMIT') AS `COM_XA_COMMIT`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='SLOW_QUERIES') AS `SLOW_QUERIES`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_ROW_LOCK_CURRENT_WAITS') AS `INNODB_ROW_LOCK_CURRENT_WAITS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_BUFFER_POOL_READS') AS `INNODB_BUFFER_POOL_READS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_BUFFER_POOL_READ_REQUESTS') AS `INNODB_BUFFER_POOL_READ_REQUESTS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='MEMORY_USED') AS `MEMORY_USED`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='BINLOG_COMMITS') AS `BINLOG_COMMITS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_BUFFER_POOL_BYTES_DATA') AS `INNODB_BUFFER_POOL_BYTES_DATA`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_DATA_WRITES') AS `INNODB_DATA_WRITES`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_OS_LOG_WRITTEN') AS `INNODB_OS_LOG_WRITTEN`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='INNODB_HISTORY_LIST_LENGTH') AS `INNODB_HISTORY_LIST_LENGTH`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_STMT_PREPARE') AS `COM_STMT_PREPARE`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='COM_STMT_EXECUTE') AS `COM_STMT_EXECUTE`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='QCACHE_QUERIES_IN_CACHE') AS `QCACHE_QUERIES_IN_CACHE`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='QCACHE_FREE_MEMORY') AS `QCACHE_FREE_MEMORY`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='QCACHE_HITS') AS `QCACHE_HITS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='QCACHE_INSERTS') AS `QCACHE_INSERTS`,
(SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS where VARIABLE_NAME='QCACHE_LOWMEM_PRUNES') AS `QCACHE_LOWMEM_PRUNES`

